name: tmp-maven-deploy

on: push

jobs:
  mvn-deploy:
    name: Mvn deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      - name: Build artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishAllPublicationsToCentralRepository
            -PmavenDeployUrl="https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            -PmavenDeployUser="${{ secrets.MAVEN_CENTRAL_USER }}"
            -PmavenDeployPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
#            -PmavenSignGpgKey="${{ secrets.MAVEN_SIGN_GPG_KEY }}"
#            -PmavenSignGpgPassword="${{ secrets.MAVEN_SIGN_GPG_PASSWORD }}"

#      - name: Upload release artifacts
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            ksmt-core/build/release/**/ksmt-core-*.jar
#            ksmt-z3/build/release/**/ksmt-z3-*.jar
#            ksmt-bitwuzla/build/release/**/ksmt-bitwuzla-*.jar
#            ksmt-yices/build/release/**/ksmt-yices-*.jar
#            ksmt-cvc5/build/release/**/ksmt-cvc5-*.jar
#            ksmt-runner/build/release/**/ksmt-runner-*.jar
